export { default as About } from "./about/About"
export { default as Header } from "./header/Header"
export { default as Skills } from "./skills/Skills"
export { default as Contact } from "./Contact/Contact"
export { default as Work } from "./work/Work"
